print("Getting to know you!\n")
name = input("What's your name? ")
fav_food = input("What's your favourite food? ")
fav_music = input("What's your favourite music ")
country = input("Where do you live? ")
print()
print(f"You are {name}")
print(f"You're probably hungry for {fav_food}")
print(f"and you're definitely getting your groove onto {fav_music}")
print(f"Living in the amazing {country}")
